apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-pipeline-run
spec:
  pipelineRef:
    name: build-deploy-pipeline
  params: 
    - name: git-url
      value: https://github.com/yuria2013/openshift-tettei-nyumon
    - name: git-revision
      value: main
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/tekton-practice/my-web
    - name: context
      value: chap18/tekton_pipeline/sample_web 
    - name: manifest-dir
      value: manifests 
  workspaces: 
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
